<?php
include"../model/sql.php";
if(isset($_POST['sub']))
{
    $key=$_POST['tenbai'];
    $id=explode("|",$key);
    $noidung=$_POST['noidung'];
    suanoidungtiethoc($id[0],$id[1],$noidung);
    if(isset($_FILES['img'])&&$_FILES['img']['size']!==0)
    {
        move_uploaded_file($_FILES['img']['tmp_name'],"./../picture/anhnoidungmonhoc/".$_FILES['img']['name']);
        suaanhtiethoc($id[0],$id[1],$_FILES['img']['name']);
    }
    
}
if(isset($_POST['xoaanh']))
{
    $key=$_POST['tenbai'];
    $id=explode("|",$key);
    $noidung=$_POST['noidung'];
    suaanhtiethoc($id[0],$id[1],"");
}
header('location:../view/tiethoc.php?this_id='.$key);
?>