<?php
include"../model/sql.php";
$id=$_POST['id'];
if(isset($_POST['sub']))
{
    
    $tenmonhoc=$_POST['tenmonhoc'];
    $oldname=$_POST['oldname'];
    $them=$_POST['name'];
    $xoa=$_POST['dele'];
    $img=$_POST['Img'];
    if(($oldname!==$tenmonhoc || isset($_FILES['img']) && $_FILES['img']['size']!==0 ))
    {
        if(isset($_FILES['img']) && $_FILES['img']['size']!==0 )
        {
            move_uploaded_file($_FILES['img']['tmp_name'],"./../picture/anhnenmonhoc/".$_FILES['img']['name']);
            xoaanh($img);
            $img=$_FILES['img']['name'];
        }
        suadulieu_baihoc($id,$tenmonhoc,$img);
        if($oldname!==$tenmonhoc)
        {
            suatenmonhoc($oldname,$tenmonhoc);
        }
    }
    if($them!=="")
    {
        themtiethoc($tenmonhoc,$them);
    }
    if($xoa!=="")
    {
        xoatiethoc($tenmonhoc,$xoa);
    }
}
if(isset($_POST['deall']))
{
    $monhoc=$_POST['tenmonhoc'];
    xoamonhoc($monhoc);
    themmonhoc($monhoc);
}
if(isset($_POST['xoaanh']))
{
    $img=$_POST['Img'];
    suadulieu_baihoc($id,$_POST['tenmonhoc'],"");
    xoaanh($img);
}
header('location:../view/chitiet.php?this_tenbai='.$id);
?>